### ISSUE TITLE
Find function strings instead of objects 

### ISSUE THREAD

**Issue by falcon027** [supercamel/SpinoDB#13]
Today a had the chance to try out the new version and I noticed that the find function now returns an array of strings instead of objects. That's not a huge problem, but it does make it a bit less simple to use, especially for newcomers to the project. I am not sure why this decision was made and what the benefits of it are. But let us reconsider the pros and cons of this again.

**Comment by supercamel** [comment]
That must have happened during the switch to Napi. It's a mistake on my behalf for not checking the return type in the previous bindings. 

I'll change it back to objects asap. It's slightly faster to return an object anyway because we can copy from a Spino dom node to a Napi object rather than stringification and re-parsing. 

As an aside I've been developing unit tests, trying to achieve maximum test coverage with all the corner cases I can possibly imagine. I had some partial test coverage of the c++ code, and of the gobject bindings but none for node bindings. But there's been far too many bugs sliding through and we're doing something about it.

**Comment by supercamel** [comment]
Fixed in d2d59321acf7a292a090747f2c8485a54ccfbd8c
