### ISSUE TITLE
Suggestion for an offset function

### ISSUE THREAD

**Issue by falcon027** [supercamel/SpinoDB#3]
In order to speed up the pagination of query results, it would be helpful to have a function which offsets the cursors start position by a defined value. 
Proposed function signature: 
`Cursor::setOffset(size_t offset) `
Let's look at an example like the table below, if one uses find() without filters the complete table gets returned. 
Table: Test: 
ID 	Name 
1 	Max 
2 	Marc 
3 	Michi 
But if the offset is set to 1 the results will look like this. 
`cursor.setOffset(1) `
ID 	Name
 2 	Marc
 3 	Michi
Are there better solutions to this Problem lets discuss it in the comments.

**Comment by supercamel** [comment]
Hi Falcon, 

This will only be of benefit if you are searching with an empty query. Generally, it is best practice to query the data by an indexed field. In this case, you have an ID column that could be indexed and searched. Functionally & performance wise, this will give you a similar result. Something like

```
find('{ID: {$gt: 1}}');
```

Cheers, Sam

**Comment by falcon027** [comment]
I tried the same approach you have described but with the _id, and I always got the error “Unknown exception caught during find query”. Please have a look at my code below:
`cursor = db.getCollection(tableName).find('{_id: {$gt:' + startIndex + '}}')`

**Comment by supercamel** [comment]
Hmm, that shouldn't throw that error. It must be a bug. I'll look into it.

**Comment by supercamel** [comment]
> 

I found & fixed the bug that caused this error. However I also realised you cannot use the _id field with a $gt query because $gt/$lt only work with numeric values and the _id field is actually a string. You should use another field for this. 
One approach might be to keep a numeric value in the key store that represents an index and increment it every time a document is added to the collection.
